name: ci-pipelines
#Reusable workflow to be called from other workflows

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version used by Maven-based jobs'
        default: '21'
        required: false
        type: string

      run_unit-tests:
        description: 'Run Unit Tests'
        default: true
        required: false
        type: boolean
      
      run_codeql:
        description: 'Run CodeQL Security Scan'
        default: false
        required: false
        type: boolean

      run_sonarqube:
        description: 'Run SonarQube Analysis'
        default: false
        required: false
        type: boolean

      enforce_quality_gate:
        description: 'Fail workflow when SonarQube Quality Gate fails'
        default: false
        required: false
        type: boolean

      run_docker:
        description: 'Run Docker Build and Push'
        default: true
        required: false
        type: boolean

      run_publish_to_dockerhub:
        description: 'Publish Docker Image to DockerHub'
        default: true
        required: false
        type: boolean

      run_publish_to_github_container_registry:
        description: 'Publish Docker Image to GitHub Container Registry'
        default: false
        required: false
        type: boolean

    secrets:
      SONAR_TOKEN:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true



jobs:
  unit-tests:
    if: ${{ inputs.run_unit-tests }}
    name: Running Unit Tests
    runs-on: arc-runner-set

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Install Maven
        run: |
          if ! command -v mvn >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y maven
          fi
          mvn -version

      - name: Run Tests + Coverage
        run: mvn -Dmaven.compiler.source=${{ inputs.java-version }} -Dmaven.compiler.target=${{ inputs.java-version }} -Dmaven.compiler.release=${{ inputs.java-version }} clean verify

      - name: Verify report exists
        run: ls -R target/site || echo "No report generated"

      # Create a directory for exported reports
      - name: Create coverage output directory
        run: mkdir -p coverage-report

      # Copy JaCoCo report into that directory
      - name: Copy coverage report
        run: cp -r target/site/jacoco/. coverage-report/

      # Upload coverage report as artifact (IMPORTANT in CI)
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-coverage-report
          path: coverage-report

  codeql:
    if: ${{ inputs.run_codeql }}
    name: CodeQL Security Scan
    runs-on: arc-runner-set

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        language: [ 'java' ]  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Install Maven
        run: |
          if ! command -v mvn >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y maven
          fi
          mvn -version

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Build with Maven
        run: mvn -Dmaven.compiler.source=${{ inputs.java-version }} -Dmaven.compiler.target=${{ inputs.java-version }} -Dmaven.compiler.release=${{ inputs.java-version }} clean compile -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "security"

  sonarqube:
    if: ${{ inputs.run_sonarqube }}
    name: Sonarqube Analysis
    runs-on: arc-runner-set
    needs: unit-tests
    steps:
      - uses: actions/checkout@v4 # v4.3.1
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      
      - name: Download coverage report artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-coverage-report
          path: coverage-report

      - name: Set up Java
        uses: actions/setup-java@v5 # v4.8.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: 'temurin' # Alternative distribution options are available.

      - name: Install Maven
        run: |
          if ! command -v mvn >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y maven
          fi
          mvn -version
      
      - name: Cache SonarQube packages
        uses: actions/cache@v4 # v4.3.0
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache Maven packages
        uses: actions/cache@v4 # v4.3.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -Dmaven.compiler.source=${{ inputs.java-version }} -Dmaven.compiler.target=${{ inputs.java-version }} -Dmaven.compiler.release=${{ inputs.java-version }} -B compile org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=Thando77_Learning-Github-Actions -Dsonar.organization=thando77 -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=coverage-report/jacoco.xml -Dsonar.working.directory=.scannerwork
      
      - name: SonarQube Quality Gate Check
        continue-on-error: ${{ !inputs.enforce_quality_gate }}
        uses: sonarsource/sonarqube-quality-gate-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  

  Docker:
    if: ${{ inputs.run_docker }}
    name: Docker Build and Push
    runs-on: arc-runner-set
    needs: sonarqube
    outputs:
      image-tag: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ inputs.java-version }}
          cache: maven

      - name: Install Maven
        run: |
          if ! command -v mvn >/dev/null 2>&1; then
            sudo apt-get update
            sudo apt-get install -y maven
          fi
          mvn -version

      - name: Build JAR with Maven
        run: mvn -Dmaven.compiler.source=${{ inputs.java-version }} -Dmaven.compiler.target=${{ inputs.java-version }} -Dmaven.compiler.release=${{ inputs.java-version }} -B clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Image Tag
        id: vars
        run: |
          IMAGE_TAGS="${{ github.run_id }}-${GITHUB_SHA::7}"
          echo "IMAGE_TAG=${IMAGE_TAGS}" >> $GITHUB_OUTPUT

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: thandrix_app:${{ steps.vars.outputs.IMAGE_TAG }}
          load: true

      - name: Save Image
        run: docker save thandrix_app:${{ steps.vars.outputs.IMAGE_TAG }} -o thandrix_app.tar

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: thandrix_app_image
          path: thandrix_app.tar  

  publish-to-dockerhub:
    if: ${{ inputs.run_publish_to_dockerhub }}
    name: Publish to DockerHub
    runs-on: arc-runner-set
    needs: Docker
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: thandrix_app_image
          path: .

      - name: Load Docker Image
        run: docker load -i thandrix_app.tar

      - name: Log in to DockerHub
        uses: docker/login-action@v2 #docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Tag Image
        run: |
          IMAGE_TAG="${{ needs.Docker.outputs.image-tag }}"
          docker image tag thandrix_app:${IMAGE_TAG} ${{ secrets.DOCKERHUB_USERNAME }}/thandrix_app:${IMAGE_TAG}

      - name: Push Image to DockerHub
        run: |
          IMAGE_TAG="${{ needs.Docker.outputs.image-tag }}"
          docker image push ${{ secrets.DOCKERHUB_USERNAME }}/thandrix_app:${IMAGE_TAG} 

  publish-to-github-container-registry:
    if: ${{ inputs.run_publish_to_github_container_registry }}
    name: Publish to GitHub Container Registry
    runs-on: arc-runner-set
    needs: Docker
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: thandrix_app_image
          path: .

      - name: Load Docker Image
        run: docker load -i thandrix_app.tar

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Image
        run: |
          IMAGE_TAG="${{ needs.Docker.outputs.image-tag }}"
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker image tag thandrix_app:${IMAGE_TAG} ghcr.io/${OWNER}/thandrix_app:${IMAGE_TAG}

      - name: Push Image to GitHub Container Registry
        run: |
          IMAGE_TAG="${{ needs.Docker.outputs.image-tag }}"
          OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker image push ghcr.io/${OWNER}/thandrix_app:${IMAGE_TAG}             
